[package]
name = "calamine_to_polars"
version = "0.1.0"
edition = "2021"

[dependencies]
# calamine = { version = "0.27.0", features = ["dates"] }
calamine = { git = "https://github.com/prophittcorey/calamine", branch = "fix/zip-3.0", features = ["dates"] }
polars = { version = "0.48.1", features = ["partition_by"] }
